### ISSUE TITLE
Java VM Android class loading error log4j-core

### ISSUE THREAD

**Issue by VeeShostak** [VeeShostak/android-aws-architecture-components-dialogflow-chatbot#6]
After updating Gradle to 3.0.1
```
Error:Execution failed for task ':app:javaPreCompileDebug'. > Annotation processors must be 
explicitly declared now.  The following dependencies on the compile classpath are found to 
contain annotation processor.  Please add them to the annotationProcessor configuration.
- log4j-core-2.2.jar (org.apache.logging.log4j:log4j-core:2.2)   Alternatively, set 
android.defaultConfig.javaCompileOptions.annotationProcessorOptions.includeCompileClasspath
= true to continue with previous behavior.  Note that this option is deprecated and will be
removed in the future.   See https://developer.android.com/r/tools/annotation-processor-error-
message.html for more details.
```

adding `log4j-core-2.2.jar (org.apache.logging.log4j:log4j-core:2.2` as dependency or setting 
`android.defaultConfig.javaCompileOptions.annotationProcessorOptions.includeCompileClasspath
= true`

gives another error:
```
Rejecting re-init on previously-failed class 
java.lang.Class<org.apache.logging.log4j.core.lookup.JmxRuntimeInputArgumentsLookup>:
java.lang.NoClassDefFoundError:
```

**Comment by VeeShostak** [comment]
To Do: try implementing solution from:
https://github.com/dialogflow/dialogflow-android-client/issues/34#issuecomment-311106345

> https://github.com/api-ai/apiai-android-client has transitive dependency on https://github.com/api-ai/apiai-java-client
Which adds log4j to your app.
log4j was not really designed to work on Android VM, so the best way to solve your issue is to use different implementation.
...
